name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          sudo apt-get -y update
          sudo apt-get -y install iptables

      - name: checkout
        uses: actions/checkout@v6

      - name: docker
        uses: docker/setup-docker-action@v4

      - name: buildx
        uses: docker/setup-buildx-action@v3

      - name: build
        run: |
          docker buildx build -f Dockerfile -o type=local,dest=. .

      - name: upload-artifact
        uses: actions/upload-artifact@v5
        with:
          name: nfc-epaper-writer
          path: |
            *.apk
          if-no-files-found: error
